### ISSUE TITLE
No image for v0.3.0

### ISSUE THREAD

**Issue by yajo** [Tecnativa/ci-base#13]
As you can see in the packages section, v0.3.0 does not have any image built:

![imagen](https://user-images.githubusercontent.com/973709/149311748-5a2c7d54-53bb-495e-b490-29c88a7c7bb7.png)

Besides, `:latest` points to v0.2.0

**Comment by joao-p-marques** [comment]
Should be fixed now. I had to run the actions again manually and it worked. We'll keep an eye on it for the next release to see if it is published correctly :+1:
